# Generated by Django 4.0.1 on 2022-01-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='request_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=30)),
                ('Phone_number', models.IntegerField()),
                ('Email_address', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
            ],
        ),
    ]
